apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  tags:
    - terraform
    - sandbox
spec:
  type: iac
  owner: ${{values.owner}}
  lifecycle: experimental

